# Site
repository: https://github.com/edumueller/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Eduardo Mauricio Mueller Nicastro
title: Fullstack DevOps Engineer
email: edu.nicastro@gmail.com
phone: +55 41 998847515
website: http://edumueller.github.io/resume

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  edumueller
stackoverflow_username: "17223963"
instagram_username: edu.mueller
linkedin_username: eduardonicastro

# Additional icon links
#additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I'm an Indutrial Engineer with professional experience as a <mark>Fullstack Engineer</mark>, and I've started pursuing a career in <mark>Cloud DevOps Engineering</mark>.

  It was a natural next step for me and has been transforming the way I work.

  What I'm looking for are opportunities to learn by helping other developers and companies build their <mark>microservices architecture</mark> and <mark>cloud infrastructure</mark>, using the most advanced technology available.
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Certificates
more_content: |
  - [Cloud DevOps Engineer](https://graduation.udacity.com/confirm/TPKMLYPS) - Udacity (`#TPKMLYPS`)
  - [React: Fullstack Web Development](https://www.udemy.com/certificate/UC-DR0ZGCB9) - Udemy (`#UC-DR0ZGCB9`)
  - [Six Sigma Green Belt](http://www.iienet2.org/IIETrainingCenter/CourseDetail.aspx?EventCode=6GB) - Institute of Industrial Engineers (`#2206-4056`)

  <div class="container education-container">
    <h3 style="border-bottom: none;">More</h3>
    <div class="col-xs-12 col-print-12">
      <p class="quote">
        I'm very interested in researching ways to apply my DevOps knowledge in manufacturing industries. With Industry 4.0, Developers and Industrial Engineers will need to work together.

        I also love CrossFit, Boxing and playing PC games.
      </p>
    </div>
  </div>

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
